# Generated by Django 3.0 on 2020-01-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
